version: 2

updates:
  - package-ecosystem: nix
    directory: "nixos/"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: "Etc/UTC"
    commit-message:
      prefix: "flake"
    groups:
      inputs:
        patterns:
          - "*"
